"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Container } from "../components/container";
import { useEffect } from "react";
import { useAuthStore } from "../store/authStore";
import axios from "../utils/axiosInstance";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Forms App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { login, logout } = useAuthStore();

  useEffect(() => {
    axios
      .get("/user/me")
      .then((res) => {
        if (res.data.email) login(res.data);
        else logout();
      })
      .catch(() => logout());
  }, []);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Container>{children}</Container>
      </body>
    </html>
  );
}
